### ISSUE TITLE
Hashlib bug when using Python 3

### ISSUE THREAD

**Issue by thiagotei** [jansel/opentuner#134]
I'm getting this error when running with Python 3.5:
```
"opentuner/search/manipulator.py", line 858, in hash_value
    return hashlib.sha256(repr(self._get(config))).hexdigest()
TypeError: Unicode-objects must be encoded before hashing
```
It looks like that for the [`PrimitiveParameter`](https://github.com/jansel/opentuner/blob/master/opentuner/search/manipulator.py#L459) it was fixed, but for the [`ComplexParameter`](https://github.com/jansel/opentuner/blob/master/opentuner/search/manipulator.py#L858) it is missing the `encode()`.

-- Thiago

**Comment by thiagotei** [comment]
The fix for [here](https://github.com/jansel/opentuner/blob/master/opentuner/search/manipulator.py#L858) would be:
```
return hashlib.sha256(repr(self._get(config)).encode('utf-8')).hexdigest().encode('utf-8')
```

**Comment by thiagotei** [comment]
@jansel

**Comment by jansel** [comment]
Thanks are you able to submit a pull request for this fix?

**Comment by thiagotei** [comment]
Yes. I’ll do that. 
(Closing and reopening this was not intentional. Clicked on the wrong button.)

**Comment by ghisloine** [comment]
Hello, code updated in repo but pip still install old version which has still TypeError. FYI

**Comment by thiagotei** [comment]
Yeah, @jansel could you update pip's version?

**Comment by jansel** [comment]
Sorry about that.  I just updated the pip version.
