### ISSUE TITLE
Choose which technique is used at each step

### ISSUE THREAD

**Issue by Agnesina** [jansel/opentuner#138]
Is there a way to choose which technique is used at each step, for example based on a external result?
Do I have to create my own "metatechnique" for this?

**Comment by jansel** [comment]
You would need to create your own meta technique for something like this.

**Comment by Agnesina** [comment]
Thank you!
Just like RoundRobinMetaSearchTechnique?

**Comment by jansel** [comment]
Yes, you can replace the selection algorithm in that with whatever you prefer.
