### ISSUE TITLE
save_to_file() error in Python 3.

### ISSUE THREAD

**Issue by NoyaFangzhou** [jansel/opentuner#141]
save_to_file() will dump the best configuration to a binary file in JSON format. However, if indicating 'wb', which is hardcoded in save_to_file() function, it will raise the error `TypeError: a bytes-like object is required, not 'str'`.

I'd like to suggest if we could change 'wb' to 'w' or let programmers pass the file-type parameters.

**Comment by jansel** [comment]
https://github.com/jansel/opentuner/commit/070c5cef6d933eb760a2f9cd5cd08c95f27aee75 should fix this
