### ISSUE TITLE
PowerOfTwoParameter search_space_size is returning wrong value

### ISSUE THREAD

**Issue by thiagotei** [jansel/opentuner#143]
The PowerOfTwoParamenter [search_space_size](https://github.com/jansel/opentuner/blob/001c61c6a3d08ad75987bb7cda12c894e7e50b20/opentuner/search/manipulator.py#L835-L836)  is returning wrong value.

The current implementation is 
`return int(math.log(super(PowerOfTwoParameter, self).search_space_size(), 2))` 
but I believe it should be
`return int(math.log(self.max_value,2) - math.log(self.min_value, 2)) + 1`

For instance, for a `PowerOfTwoParameter(k, 2, 32)` it returns 4 but should return 5.

**Comment by jansel** [comment]
I think you are right.  Want to submit a PR to fix it?

**Comment by thiagotei** [comment]
Yes, I will work on it.
