### ISSUE TITLE
Autoreformat?

### ISSUE THREAD

**Issue by kaomoneus** [jansel/opentuner#146]
Hi! I've noticed, that few months ago there was an [auto-reformat commit](https://github.com/jansel/opentuner/commit/2d23d76a9a15eb953e405c3263aa74ce9b8adbd2). But it seems that you also changed some logic there.

Assuming, that you squashed few commits, is it possible to add some description to that change... or it would be really great, if you publish unsquashed branch. Thanks!

**Comment by jansel** [comment]
There shouldn't be any logic changes in that commit.

**Comment by kaomoneus** [comment]
Ok! Please give me one day we will recheck.

**Comment by kaomoneus** [comment]
Thanks! Indeed there were no logical changes.
