### ISSUE TITLE
PatternSearch bug

### ISSUE THREAD

**Issue by YanChurkin** [jansel/opentuner#148]
Hi! Here was fixed a PatterSearch technique bug. 

https://github.com/jansel/opentuner/commit/001c61c6a3d08ad75987bb7cda12c894e7e50b20

Can you please explain this bug nature in more detail, I cannot find another issues in this repo?

**Comment by jansel** [comment]
`.sort(cmp=...)` no longer works in python3.  The `cmp=` keywork arg was removed.  That diff is a refactor to not use `cmp=`

**Comment by YanChurkin** [comment]
> `.sort(cmp=...)` no longer works in python3. The `cmp=` keywork arg was removed. That diff is a refactor to not use `cmp=`

Thank you for explanation! Good luck!
