### ISSUE TITLE
enabling https on opentuner.org

### ISSUE THREAD

**Issue by jensengrey** [jansel/opentuner#151]
https doesn't work against opentuner.org 

https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/about-custom-domains-and-github-pages

https://docs.github.com/en/pages/getting-started-with-github-pages/securing-your-github-pages-site-with-https

**Comment by jansel** [comment]
Thanks for point this out!  Should be fixed now.  For some reason I needed to delete and re-add the custom domain for it to work.
