### ISSUE TITLE
Search algorithm setting

### ISSUE THREAD

**Issue by ningmengwei-ata** [jansel/opentuner#153]
Can I ask how to set the specific search algorithm when I'm using opentuner to optimize a C program? Thanks!

**Comment by jansel** [comment]
`'--technique=...` on the command line.  See also `--list-techniques` and `opentuner.search.technique.register()`

https://github.com/jansel/opentuner/blob/master/opentuner/search/technique.py#L26

**Comment by ningmengwei-ata** [comment]
Thanks very much! Can I ask how to implement grid search in this opentuner, how to traverse the parameters? I have understood the way to use a search technique but I don't know how to implement the grid search in opentuner.

**Comment by jansel** [comment]
Grid search is rather similar to [PatternSearch](https://en.wikipedia.org/wiki/Pattern_search_(optimization)) found here: https://github.com/jansel/opentuner/blob/master/opentuner/search/patternsearch.py -- so you could use that as a starting point for adding grid search.

Once you implement a new technique call `opentuner.search.technique.register(YourSearchAlgoritm(name="foo"))` to register it then pass `--technique=foo` to use it.
