### ISSUE TITLE
Question to define the parameters with relationships

### ISSUE THREAD

**Issue by leslie-fang-intel** [jansel/opentuner#157]
Hi @jansel, I have a question to define parameters for my tuning case. 
I have 3 parameters to tune:

- Parameter1:  A `EnumParameter` with a list of candidates, for example [1, 2, 4, 7, 14, 28]
- Parameter2: 1. Pick from a range of min and max integer (user inputs). 2. Must be divisible by `Parameter1`.
- Parameter3:  Pick from a range between min and max integer. The min integer is 1. The max integer should be `Parameter2//Parameter1`.

Could you kindly help to take a look how can I define these parameters in openTuner to tune?

**Comment by jansel** [comment]
There are a few options.  One way would be to override `Parameter.normalize()` to map invalid configs to the "closest" valid config.  Or implement a custom Parameter subclass to encode your constraints.

Another option, that might be easier, would be to rewrite your search space in a way where all points are valid.  For your example, you could reframe your problem in terms of more primitive parameters:
```
p1 = a
p2 = a * b
p3 = round(c*(p2//p1-1))
```

`a` would be the same enum.  `b` would be an interger. `c` would be a float from 0 to 1.

This mapping encodes your constraints as a projection in configuration space.

**Comment by leslie-fang-intel** [comment]
Thanks for the reply, I will take a try.
