### ISSUE TITLE
Set Max Function Evaluation?

### ISSUE THREAD

**Issue by TianningGao** [jansel/opentuner#163]
Assume that I'm optimizing the Rosenbrock function, is there a way to let OpenTuner stop after a pre-defined number of function evaluations?

Another questions is, if I have an initial dataset of the Rosenbrock function, how to pass it into OpenTuner?

**Comment by jansel** [comment]
From `--help`

> Assume that I'm optimizing the Rosenbrock function, is there a way to let OpenTuner stop after a pre-defined number of function evaluations?

```
  --test-limit TEST_LIMIT
                        stop tuning after given tests count

```

> Another questions is, if I have an initial dataset of the Rosenbrock function, how to pass it into OpenTuner?

```
  --seed-configuration FILENAME
                        Start search at a given configuration. Can be specified multiple times. Configurations are
                        loaded with ConfigurationManipulator.load_from_file() and file format is detected from
                        extension.
```

**Comment by TianningGao** [comment]
Thank you for your responding!
Also, is there any example of the seed configuration file? I need to know the data format in that file.

**Comment by jansel** [comment]
It is the same json file format that is output for the final config found.

**Comment by TianningGao** [comment]
Got it. Thank you so much!
