### ISSUE TITLE
Question for execution time measurement

### ISSUE THREAD

**Issue by yingluosanqian** [jansel/opentuner#170]
I have some doubts about the program's execution time. I noticed that the code related to measuring the program's execution time is in this file `opentuner/measurement/driver.py`, where the `lap_timer` function is used to calculate the time difference between the last call to the function and the current call.

From my understanding, this method is not reasonable for programs with short execution times (e.g., those running within a second), because the measured time actually includes the time spent by the Python program itself and the time for process calls. Additionally, I don't seem to see any warm-up procedure or multiple iterations to calculate an average (did I miss something?).

Has there been any consideration to use tools like `perf` to measure the program's execution time? If not, what is the reason for not using it?

**Comment by jansel** [comment]
The `lap_timer` function in `driver.py` is just used for logging, it is not the objective opentuner is trying to optimize.

You can use whatever mechanism you like to perform measurement, as an example measurement is overriden here:
https://github.com/jansel/opentuner/blob/ed92a56197a2cb4c7a0203150f6976d7f3506507/examples/halide/halidetuner.py#L427-L433
in that example timing is actually done [in C++](https://github.com/jansel/opentuner/blob/master/examples/halide/timing_prefix.h) then parsed in Python.

Other examples don't even use execution time as the thing being optimized.  In general, it is up to the user how to do the measurement properly.

**Comment by yingluosanqian** [comment]
Thank you! I got it.
