### ISSUE TITLE
SearchObjective.limit_from_config crashes - needs check for no results?

### ISSUE THREAD

**Issue by vdelvecc** [jansel/opentuner#63]
I was getting periodic crashes in SearchObjective.limit_from_config saying something about max not having any arguments.  I seemed to notice it more when I increased parallelism.

I was able to fix them by imitating ThresholdAccuracyMinimizeTime.limit_from_config and returning None if results.count() == 0.

Seem reasonable to do the check in both places?

**Comment by jansel** [comment]
This seems like a reasonable fix.  Can you make a pull request?
