### ISSUE TITLE
Mario Example: Create Movie file from Database

### ISSUE THREAD

**Issue by matthiastz** [jansel/opentuner#90]
I could run the mario example with the [following command](http://opentuner.org/slides/opentuner-cgo2015-hands-on.pdf) 
`./mario.py --technique=PSO_GA_Bandit --parallelism=X --stop-after=Y --headful --representation=DurationRepresentation --fitness-function=ProgressTimesAverageSpeed` 
(btw without the parameter `--headful` i can't run it, i get an error) 

I chose X=8 because my cpu has 8 threads and Y=15*60 ... and mario made it with config_id=203 (and tuning_run=1) to the end :+1: :+1: 

Now after the tuning run, i wanted to generate the movie file from the database. 
I run: `./mario.py --tuning-run=1 > tuning-run-1.fm2` 

and get this error written to `tuning-run-1.fm2`:
`must specify --database`

So, i tried to specify the database:
`./mario.py --tuning-run=1 > tuning-run-1.fm2 --database=opentuner.db`

again i get an error:

> Traceback (most recent call last):
>   File "./mario.py", line 297, in <module>
 >    new_bests_movie(args)
>   File "./mario.py", line 282, in new_bests_movie
  >   (stdout, stderr) = subprocess.Popen(["sqlite3", args.database, "select configuration_id from result >  where tuning_run_id = %d and was_new_best = 1 order by collection_date;" % args.tuning_run], 
> stdout=subprocess.PIPE, stderr=subprocess.PIPE).communicate()
> TypeError: %d format: a number is required, not str

...

if i change in line 282 the `%d` format to `%s` or cast the value to `int(args.tuning_run)`
i get an error too:

> Traceback (most recent call last):
>   File "./mario.py", line 297, in <module>
>     new_bests_movie(args)
>   File "./mario.py", line 282, in new_bests_movie
>     (stdout, stderr) = subprocess.Popen(["sqlite3", args.database, "select configuration_id from result where tuning_run_id = %s and was_new_best = 1 order by collection_date;" % args.tuning_run], stdout=subprocess.PIPE, stderr=subprocess.PIPE).communicate()
>   File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
>     errread, errwrite)
>   File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
>     raise child_exception
> OSError: [Errno 2] No such file or directory

---

can you guys please help me extracting that movie file?
is there a other way to get that movie file?
(i cloned the newest version of your framework and build the fceux from source, working on debian/ubuntu) Thanks.

**Comment by jbosboom** [comment]
If you run

    sqlite3 opentuner.db 'select configuration_id from result where tuning_run_id = 1 and was_new_best = 1 order by collection_date;'

on the command line, what output do you get?

If that command gives you an error about not opening the database, try `opentuner.db/<hostname>.db` instead, replacing `<hostname>` with your machine's hostname.

**Comment by matthiastz** [comment]
```
sqlite3 opentuner.db/matthias.db 'select configuration_id from result where tuning_run_id = 1 and was_new_best = 1 order by collection_date;'
```
gives me:

> 1
> 2
> 6
> 8
> 9
> 23
> 45
> 50
> 84
> 93
> 96
> 150
> 162
> 180
> 203

... which are the exact same values from the database (i opened the db with sqlite browser and ordered by "was_new_best = 1")
so the database request seem to work, right? what would be the next step?

**Comment by matthiastz** [comment]
i don't want to bother you guys - but - do you have a potential workaround to get that movie file? in near future i want to give a presentation about your framework at university in Germany - and would like to show that example (and more) and its result there :)

**Comment by jbosboom** [comment]
Sorry, I expected GitHub to send me a follow-up e-mail when you replied.  I'll look into it in the next couple of days.

To be clear, when you run `mario.py`, you passed `--database=opentuner.db/matthias.db` (as you did in the `sqlite3` command)?

My initial hypothesis was that you didn't have the sqlite3 command available or it had some problem using the database, but if it works at the command line, then the problem is in the script.  It works for me (of course), so I'll have to see if I can get more error information from `subprocess.communicate` as to what exactly is going wrong.

**Comment by matthiastz** [comment]
no problem, i appreciate your help.

i tried both ways of passing the db parameter, interesting fact: if i just pass the "folder" of the db path and not the whole path, i get no error - but if i pass the whole path i get an error:

![mario1](https://cloud.githubusercontent.com/assets/23010759/21563220/224ec574-ce80-11e6-9bb3-f925b6f2868c.png)

(here it is `debian.db` and not `matthias.db` because i work on 2 different machines)

btw, i modified the script `mario.py` a little - this is the actual status:
```
def new_bests_movie(args):
# change 1: %d -> %s
# change 2: sqlite3 -> /usr/bin/sqlite3
  (stdout, stderr) = subprocess.Popen(["/usr/bin/sqlite3", args.database, "select configuration_id from result where tuning_run_id = %s and was_new_best = 1 order by collection_date;" % args.tuning_run], stdout=subprocess.PIPE, stderr=subprocess.PIPE).communicate()
```

here the output of the .fm2 file (no matter what type of command i use):
```
version 3
emuVersion 9828
romFilename smb.nes
romChecksum base64:jjYwGG411HcjG/j9UOVM3Q==
guid 51473540-E9D7-11E3-ADFC-46CE3219C4E0
fourscore 0
port0 1
port1 1
port2 0

seems like the change with the sqlite command in the script doesn't change the result :(
```

**Comment by jbosboom** [comment]
Okay, passing the whole database path is actually working, but because you didn't pass the `--representation=` option, `new_bests_movie` can't interpret the database parameters back to a movie file.  You need to pass the same value for `--representation=` as you did when doing the tuning run.

**Comment by matthiastz** [comment]
![mario2](https://cloud.githubusercontent.com/assets/23010759/21573094/e00b0004-cee0-11e6-96fb-8b611f07fffd.png)

**Comment by jbosboom** [comment]
Is this on the same machine that you ran the tuning run on?  It doesn't have to be the exact same machine, but it will run all the new-bests in the emulator, so the emulator and ROM need to be available.  You may also have to pass `--headful` if you don't have `xvfb-run` available.

**Comment by matthiastz** [comment]
yes i did a tuning run on the same machine before (debian.db) ... emu & rom were available.
`--headful` does the job. i should have tried that on my own, but now the command works. the movie file gets written, but there are **always multiple "replays/trys"** in one movie file:
[tuning-run-1-copy-fm2.txt](https://github.com/jansel/opentuner/files/679623/tuning-run-1-copy-fm2.txt)

is there a way to "strip" these multiple trys in one movie file? in the first column there is sometimes a 1 instead of a 0 ... does that intend a new replay? if so, i could strip them on my own

i will do a fresh tuning run on my faster machine in a few days, and use that for my presentation. thanks a lot =)

**Comment by jbosboom** [comment]
> there are always multiple "replays/trys" in one movie file

Well, that's what the new-bests movie is.  It shows each new best tuning trial, so you can see how OpenTuner made progress.

> in the first column there is sometimes a 1 instead of a 0 ... does that intend a new replay?

Yes, a 1 indicates the emulator should simulate the console's reset button being pressed.

**Comment by jbosboom** [comment]
@matthiastz With the changes in #96, the tuner will now write a movie file containing just the best configuration when the tuning run finishes.  Those changes also fix some of the problems you ran into trying to generate the new-bests movie file.

**Comment by matthiastz** [comment]
thanks, i will take a look at it
