### ISSUE TITLE
Default parameters 

### ISSUE THREAD

**Issue by bbodin** [jansel/opentuner#93]
Hello,

What is the most appropriate way to add a default/expert configuration to the list of evaluated configurations ? 
I currently do it manually, but adding it in OpenTuner process would make sense. it would also provide more consistent results I guess.

Thanks,

**Comment by jansel** [comment]
Take a look at `--seed-configuration`

```
argparser.add_argument('--seed-configuration', action='append', default=[],
                       metavar='FILENAME', help="""
                           Start search at a given configuration.  Can be
                           specified multiple times.  Configurations are loaded
                           with ConfigurationManipulator.load_from_file()
                           and file format is detected from extension.""")
```

**Comment by bbodin** [comment]
Thanks ! 
This led me to reimplement in my Interface class:
```
 def seed_configurations(self):
    return [{...default_configuration...}]
```
Which did the job very well.
